apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch-echo
  labels:
    app: dispatch-echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dispatch-echo
  template:
    metadata:
      labels:
        app: dispatch-echo
    spec:
      serviceAccountName: dispatch-echo
      containers:
      - name: dispatch-echo  
        image: jonwhit/dispatch-echo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
